name: Build Rust Windows App

on:
  push:
    branches: [ "main" ] # 当你提交代码到 main 分支时自动触发
  workflow_dispatch:     # 允许你手动点击按钮触发编译

jobs:
  build:
    runs-on: windows-latest # 指定使用 Windows 云服务器编译

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release
      run: cargo build --release # 编译 Release 版本，体积更小，运行更快

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: JustEnglishMode-App
        path: target/release/*.exe # 自动将编译好的 exe 文件打包供你下载
